config/routes.rb
LunchTyme::Application.routes.draw do
  resources :friendships

  resources :users

  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
end

app/models/lunch_pairer.rb
class LunchPairer
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friendship = Friendship.new(friendship_params)

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: 'Friendship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @friendship }
      else
        format.html { render action: 'new' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to friendships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :first_name, :last_name, :netid, :class_year, :res_col, :email, :phone_number, :gender, :friends, :likes, :mutual_friends, :object_me, :facebook_id, :provider, :oauth_token, :oauth_expires_at, :last_pull_from_facebook, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<h1>Listing friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.status %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friendship.status %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchTyme</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :netid %><br>
    <%= f.text_field :netid %>
  </div>
  <div class="field">
    <%= f.label :class_year %><br>
    <%= f.number_field :class_year %>
  </div>
  <div class="field">
    <%= f.label :res_col %><br>
    <%= f.text_field :res_col %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :friends %><br>
    <%= f.text_area :friends %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.text_area :likes %>
  </div>
  <div class="field">
    <%= f.label :mutual_friends %><br>
    <%= f.text_area :mutual_friends %>
  </div>
  <div class="field">
    <%= f.label :object_me %><br>
    <%= f.text_area :object_me %>
  </div>
  <div class="field">
    <%= f.label :facebook_id %><br>
    <%= f.number_field :facebook_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br>
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_expires_at %><br>
    <%= f.datetime_select :oauth_expires_at %>
  </div>
  <div class="field">
    <%= f.label :last_pull_from_facebook %><br>
    <%= f.datetime_select :last_pull_from_facebook %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Netid</th>
      <th>Class year</th>
      <th>Res col</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Gender</th>
      <th>Friends</th>
      <th>Likes</th>
      <th>Mutual friends</th>
      <th>Object me</th>
      <th>Facebook</th>
      <th>Provider</th>
      <th>Oauth token</th>
      <th>Oauth expires at</th>
      <th>Last pull from facebook</th>
      <th>Image url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.netid %></td>
        <td><%= user.class_year %></td>
        <td><%= user.res_col %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.gender %></td>
        <td><%= user.friends %></td>
        <td><%= user.likes %></td>
        <td><%= user.mutual_friends %></td>
        <td><%= user.object_me %></td>
        <td><%= user.facebook_id %></td>
        <td><%= user.provider %></td>
        <td><%= user.oauth_token %></td>
        <td><%= user.oauth_expires_at %></td>
        <td><%= user.last_pull_from_facebook %></td>
        <td><%= user.image_url %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Netid:</strong>
  <%= @user.netid %>
</p>

<p>
  <strong>Class year:</strong>
  <%= @user.class_year %>
</p>

<p>
  <strong>Res col:</strong>
  <%= @user.res_col %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Friends:</strong>
  <%= @user.friends %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @user.likes %>
</p>

<p>
  <strong>Mutual friends:</strong>
  <%= @user.mutual_friends %>
</p>

<p>
  <strong>Object me:</strong>
  <%= @user.object_me %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @user.facebook_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Oauth token:</strong>
  <%= @user.oauth_token %>
</p>

<p>
  <strong>Oauth expires at:</strong>
  <%= @user.oauth_expires_at %>
</p>

<p>
  <strong>Last pull from facebook:</strong>
  <%= @user.last_pull_from_facebook %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @user.image_url %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>